# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AllAbout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftLint'
pod 'Firebase/Database','6.24.0'
pod 'Firebase/Auth','6.24.0'
pod 'Firebase/Firestore','6.24.0'
pod 'Firebase/Storage'
pod 'AlamofireImage', '~> 4.1'
pod 'JGProgressHUD'
pod 'IQKeyboardManagerSwift'

end
